### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Smekalin** [single-spa/single-spa.js.org#369]
Hi! Have we now work for Russian translation in progress? If not I want to write it. Can you create `ru.single-spa.js.org` repo?

**Comment by internettrans** [comment]
Hi @Smekalin - thanks for offering to help with this. We do not have a russian translation yet. Do you know of any others who can help you with the translation. We prefer having at least two people helping with the translation.

Also, for reference, here was the discussion about the Spanish translation: https://github.com/single-spa/single-spa.js.org/issues/317.

### Tasks for me

- [x] Decide on a language code to use. I agree that `ru` is good.
- [x] Create a new repo called `ru.single-spa.js.org`. **Manually** initialize it to be the same git tree as single-spa.js.org. Do not do this by forking the repo -- a fork has a separate git tree. You can do this by initializing to empty repo (no readme, no gitignore) and then adding that as a remote to your local copy of `single-spa.js.org`:
```sh
cd single-spa.js.org
git remote add ru git@github.com:single-spa/ru.single-spa.js.org.git
git push ru master:master
```
- [ ] Set up the bot to automatically commit to ru.single-spa.js.org whenever a PR is merged into single-spa.js.org. When a merge conflict happens, a pull request is created instead of a commit to master. We're currently doing this with https://github.com/guguji5/sync-fork-repo, but i don't think it is yet set up to handle more repos besides the `zh-hans` repo. @guguji5 can you clarify? Perhaps should we transfer that repository into https://github.com/single-spa so that it's owned and managed by you, the single-spa core team, and other translators.
- [x] Update docusaurus config to correct domain https://github.com/single-spa/ru.single-spa.js.org/commit/b8097893831736e3920d8d22a528c4f2458cbfad
- [x] Update CircleCI badge in readme to correct url https://github.com/single-spa/ru.single-spa.js.org/commit/e6660e0cdd2afb7c340b5362240d8f2f15721f76
- [x] Enable builds in CircleCI. Add the GITHUB_TOKEN env variable
- [x] Modify [`/website/static/CNAME`](https://github.com/single-spa/single-spa.js.org/blob/master/website/static/CNAME) in to be the correct domain. https://github.com/single-spa/ru.single-spa.js.org/commit/7bd77eb4e50f607dbbb32faca64db052feb0ce3e
- [x] Force HTTPS in the repository settings in Github. This takes a day or so after the CNAME is set for the SSL cert to be set up.
- [x] Create a pull request to the js.org repo, adding the subdomain. Should be similar to this: https://github.com/js-org/js.org/pull/3747
- [x] Add Russian to [translations.js](https://github.com/single-spa/single-spa.js.org/blob/master/website/src/data/languages.js), so that it appears in the list at https://single-spa.js.org/languages

### Tasks for @Smekalin 

- [x] Find at least one other person besides @Smekalin who can help with the translations.
- [ ] [Watch the ru.single-spa.js.org Github repository](https://docs.github.com/en/enterprise-server@2.20/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-repositories) for all activity
- [ ] Translate the files `/website/versioned_docs/version-5.x` directory. Do not translate the `/docs` directory. Also, translate each of the pages in `/website/pages`

**Comment by internettrans** [comment]
The repository is at https://github.com/single-spa/ru.single-spa.js.org

**Comment by internettrans** [comment]
Pull request for the subdomain is at https://github.com/js-org/js.org/pull/5037

**Comment by astra1** [comment]
@Smekalin  @joeldenning Hello! I would like to help you with Russian translation

**Comment by Smekalin** [comment]
@astra1 Thank you! I don't have a permissions for create a branch in ru-repo now.

I forked ru-repo (https://github.com/Smekalin/ru.single-spa.js.org) and started translate it in fork repo.

@joeldenning Can you give me and @astra1 permissions for push branches? Or should we do it in fork repo?

**Comment by internettrans** [comment]
I gave you both permissions to the repo. You can accept the invitation in your email, or at github.com/single-spa.

**Comment by internettrans** [comment]
I added russian to translations.js - see https://github.com/single-spa/single-spa.js.org/blob/master/website/src/data/languages.js.

**Comment by internettrans** [comment]
It is live!

https://single-spa.js.org/languages

https://ru.single-spa.js.org/

**Comment by internettrans** [comment]
@guguji5 can you help set up the bot to sync code from single-spa.js.org to ru.single-spa.js.org?

@astra1 @Smekalin can you both [Watch the ru.single-spa.js.org repository for all activity](https://docs.github.com/en/enterprise-server@2.20/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-repositories)?

**Comment by internettrans** [comment]
Also, @astra1 and @Smekalin could you join the [single-spa slack workspace](https://join.slack.com/t/single-spa/shared_invite/zt-j4c38g92-JmV7O~35dkN1CnaBkK7NTw) and then join the `#translations` channel and say hello there?

**Comment by internettrans** [comment]
@guguji5 can you confirm whether the bot is set up for ru.single-spa.js.org? If not, I will look into setting it up myself.

**Comment by guguji5** [comment]
@joeldenning The sync script failed because of some reason, I fix it and add bot for ru.single-spa.js.org. 

it works as expect (https://github.com/single-spa/ru.single-spa.js.org/pull/4)

now it runs at every 0:00, I will check it tomorrow.

**Comment by internettrans** [comment]
Thanks!
