### ISSUE TITLE
hindi

### ISSUE THREAD

**Issue by nadeemkhanrtm1** [single-spa/single-spa.js.org#467]
I want Hindi Language on your website

**Comment by internettrans** [comment]
Hi @nadeemkhanrtm1, do you know anyone else who can help with the translation? We prefer having at least two people helping with the translation.

For reference, here was the issue for adding the Russian translation: https://github.com/single-spa/single-spa.js.org/issues/369

Here's the checklist for what needs to be done. Once we confirm there are at least two people willing to help with the translation, I'll start doing them.

### Tasks for me

- [ ] Decide on a language code to use. I agree that `id` is good.
- [ ] Create a new repo called `id.single-spa.js.org`. **Manually** initialize it to be the same git tree as single-spa.js.org. Do not do this by forking the repo -- a fork has a separate git tree. You can do this by initializing to empty repo (no readme, no gitignore) and then adding that as a remote to your local copy of `single-spa.js.org`:
```sh
cd single-spa.js.org
git remote add id git@github.com:single-spa/id.single-spa.js.org.git
git push id master:master
```
- [ ] Update docusaurus config to correct domain (example at https://github.com/single-spa/ru.single-spa.js.org/commit/b8097893831736e3920d8d22a528c4f2458cbfad)
- [ ] Update CircleCI badge in readme to correct url (example at https://github.com/single-spa/ru.single-spa.js.org/commit/e6660e0cdd2afb7c340b5362240d8f2f15721f76)
- [ ] Enable builds in CircleCI. Add the GITHUB_TOKEN env variable
- [ ] Modify [`/website/static/CNAME`](https://github.com/single-spa/single-spa.js.org/blob/master/website/static/CNAME) in to be the correct domain. https://github.com/single-spa/id.single-spa.js.org/commit/7bd77eb4e50f607dbbb32faca64db052feb0ce3e
- [ ] Force HTTPS in the repository settings in Github. This takes a day or so after the CNAME is set for the SSL cert to be set up.
- [ ] Create a pull request to the js.org repo, adding the subdomain. Should be similar to this: https://github.com/js-org/js.org/pull/3747
- [ ] Add Indonesian to [translations.js](https://github.com/single-spa/single-spa.js.org/blob/master/website/src/data/languages.js), so that it appears in the list at https://single-spa.js.org/languages

### Tasks for @nadeemkhanrtm1   

- [ ] Find at least one other person who can help with the translations.
- [ ] [Watch the id.single-spa.js.org Github repository](https://docs.github.com/en/enterprise-server@2.20/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-repositories) for all activity
- [ ] Translate the files `/website/versioned_docs/version-5.x` directory. Do not translate the `/docs` directory. Also, translate each of the pages in `/website/pages`

### Tasks for @guguji5

- [ ] Set up the bot to automatically commit to id.single-spa.js.org whenever a PR is merged into single-spa.js.org.
